### ISSUE TITLE
How to reset the environment?

### ISSUE THREAD

**Issue by zhbh01** [facebookresearch/minirts#4]
The example in minirts/scripts/behavior_clone/match2.py only shows one episode of the game at each thread. So how can I reset the game state at the end of an episode? I want to train RL algorithms with it.

**Comment by jwhj** [comment]
Did you find a way to reset the environment?

**Comment by zhbh01** [comment]
It seems that the reset python API is not implemented, so you can't reset the environment manually in your python script. However, you can find a reset function header in game/engine/game_base.h file, and this function is called in the main loop of each thread. It is possible to implement a reset API yourself.
